load("membership_pols.py")
load("functions_nilp_lie_alg.py")
load("invariants_nilp_lie_alg.py")
load("characteristics.py")
load("matrix_derivation_invariants.py")
load("solvable_invariants.py")
load("nilpotent_lie_algebra.py")
load("solvable_lie_algebra.py")
